version: "3.9"
services:
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=dish
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ./db/dish/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
  app:
    image: dish
    container_name: dish
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/dish
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    ports:
      - "127.0.0.1:8081:8081"
    depends_on:
      - db
